### ISSUE TITLE
为什么点了切到搜题了，但是搜题总是提示获取题目失败，从没搜题成功过，怎么回事啊

### ISSUE THREAD

**Issue by lnxglycyq1971** [lgpersonal/LazyStudy#12]

**Comment by keep-an** [comment]
> _没有提供描述。_
把代码改一下就行了   微信窗口控件抓不到
    if (textContains("强国挑战").exists()) {
        //toastLog("正在切换小程序");
        click("强国挑战");
    } else {
            launch("com.tencent.mm");
    sleep(2000);
    desc("搜索").findOnce().click();
    //className("android.widget.ImageView").id("r_").findOnce().click();
    sleep(1000);
    //click("小程序");
    //sleep(1000);
    setText("强国挑战答题答案查询");
    sleep(1000);
    textContains("搜一搜").findOnce().parent().click();
    sleep(1000);
    text("小程序").findOnce().click();
    sleep(1000);
    var h=device.height;//屏幕高
    var w=device.width; 
    click(w/2,h/4);
    sleep(1000);
    click(w/2,h/5);
    sleep(2000);
    click(w/2,h/6);
    }

**Comment by lgpersonal** [comment]
获取题目失败？呃……进入挑战答题后，点击挑战答题，如果失败退出答题再进入答题。有时候是布局捕获不正常

**Comment by keep-an** [comment]
> 获取题目失败？呃……进入挑战答题后，点击挑战答题，如果失败退出答题再进入答题。有时候是布局捕获不正常

重构每日答题用着挺顺     挑战答题以前没问题   重构之后通过tikuCommon中转就经常出现获取题目失败

**Comment by lnxglycyq1971** [comment]
> _No description provided._
