### ISSUE TITLE
请问这个网站禁止外部提交，有啥好办法没？

### ISSUE THREAD

**Issue by lgpersonal** [lgpersonal/LazyStudy#16]
这个网站禁止外部提交，有啥好办法没？目前尝试先获取 cookie再post，失败。

```
var url = "https://mtear.cn/xx/?";

var r = http.get(url);
var cookie = r.headers["Set-Cookie"].toString();
console.log(cookie);

var opt = {};
opt.headers = {
    'Origin': 'https://mtear.cn',
    'Referer': 'https://mtear.cn/xx/?',
    'Cookie': cookie
};
var dataStr = "time=%D1%A7%CF%B0%C7%BF%B9%FA%CC%F4%D5%BD%B4%F0%CC%E2&name=%B6%FE%CA%AE%CB%C4%CA%B7&button=%C1%A2%BC%B4%B2%E9%D1%AF";
var dataArray = {
    "time": "学习强国挑战答题",
    "name": "二十四史",
    "button": "立即查询"
};
var r2 = http.post(url, dataArray,opt);
var resStr = r2.body.string();

var indexTable = resStr.indexOf("table");
if (indexTable >= 0) {
    console.log("成功");
    console.log(resStr.substr(indexTable));
} else {
    console.log("失败");
};
```

**Comment by keep-an** [comment]
> 这个网站禁止外部提交，有啥好办法没？目前尝试先获取 cookie再post，失败。
> 
> ```
> var url = "https://mtear.cn/xx/?";
> 
> var r = http.get(url);
> var cookie = r.headers["Set-Cookie"].toString();
> console.log(cookie);
> 
> var opt = {};
> opt.headers = {
>     'Origin': 'https://mtear.cn',
>     'Referer': 'https://mtear.cn/xx/?',
>     'Cookie': cookie
> };
> var dataStr = "time=%D1%A7%CF%B0%C7%BF%B9%FA%CC%F4%D5%BD%B4%F0%CC%E2&name=%B6%FE%CA%AE%CB%C4%CA%B7&button=%C1%A2%BC%B4%B2%E9%D1%AF";
> var dataArray = {
>     "time": "学习强国挑战答题",
>     "name": "二十四史",
>     "button": "立即查询"
> };
> var r2 = http.post(url, dataArray,opt);
> var resStr = r2.body.string();
> 
> var indexTable = resStr.indexOf("table");
> if (indexTable >= 0) {
>     console.log("成功");
>     console.log(resStr.substr(indexTable));
> } else {
>     console.log("失败");
> };
> ```

你可以试试这个题库网站http://49.235.90.76:5000/
