### ISSUE TITLE
建议答题每一道题、评论、分享、收藏之间不要提交得太快。

### ISSUE THREAD

**Issue by leongfeng** [lgpersonal/LazyStudy#28]
评论、分享、收藏三个功能速度太快，答题提交答案速度也太快了。
这样太容易被判断出是刷分了。建议在这些功能之间弄个随便数，暂停一下，以便模拟成真人操作。

**Comment by 4avast** [comment]
> 评论、分享、收藏三个功能速度太快，答题提交答案速度也太快了。
> 这样太容易被判断出是刷分了。建议在这些功能之间弄个随便数，暂停一下，以便模拟成真人操作。

事实上，没有你想想的这么严苛。
首先.收评分三个功能只有最后一个删评论的行为 可能会被判定为机刷 也仅仅是可能。 因为正常人不会天天天天评论完就删除，这个你应该能理解。
第二 答题速度并不快，我们单位组织的答题比赛 1240到题 刷通关只要34-40分钟，机器刷可比这个慢多了。刷通关那些人天天练习比速度，没有见被封过。
第三。现在的问题是 如何提高答题正确率，目前的题库还是有很多错答案，让人很抓狂。

**Comment by leongfeng** [comment]
这样呀，不过为了避免被封号，我自己答题时会暂停一下。然后再继续
