### ISSUE TITLE
无法收藏评论分享

### ISSUE THREAD

**Issue by yd331644359** [lgpersonal/LazyStudy#31]
![Screenshot_2020-02-27-13-28-28-818_cn xuexi android](https://user-images.githubusercontent.com/56525556/75420438-fdf42080-5972-11ea-9741-8562a7c1df7f.png)

**Comment by yd331644359** [comment]
手机mix2，版本2.50和2.51都不行

**Comment by yd331644359** [comment]
15:09:55.407/E: Thread[ScriptThread-20[/data/user/0/com.lazyStudy/files/project/floating.js] (Spawn-0),5]: TypeError: Cannot call method "drawingOrder" of null (file:/data/data/com.lazyStudy/files/project/collectCommentShare.js#15)
TypeError: Cannot call method "drawingOrder" of null
    at main (file:/data/data/com.lazyStudy/files/project/collectCommentShare.js:15:0)
    at floating.js.js:107:0

**Comment by lgpersonal** [comment]
收藏评论转发，是要进入文章界面。你这是在主界面，还没打开文章

**Comment by yd331644359** [comment]
原来如此！

**Comment by 4avast** [comment]
请删除此Issue。
