### ISSUE TITLE
填空题挂了，选择题还可以。学习强国换旧版填空题同样也不行。

### ISSUE THREAD

**Issue by gaoyaodad** [lgpersonal/LazyStudy#60]
作者大大，填空题做不了了，选择题还正常。学习强国降级安装了，填空题还是做不了。看到不是我一个人的问题，我就不捯饬了。卸载重装了半天。搜了一下，明明题库里面有对应的的题目，但是就是没能识别和填充。

**Comment by lgpersonal** [comment]
刚更新了，你们试试
