### ISSUE TITLE
今天强国升级，本地浏览灰色，导致浏览不能继续，

### ISSUE THREAD

**Issue by adamnb1** [lgpersonal/LazyStudy#71]

**Comment by Mr-zhao98** [comment]
我的也是，今天学习强国  版本大更新了  很多界面不一样

**Comment by Mr-zhao98** [comment]
点一下  开始浏览  界面就停那不动了

**Comment by enoang** [comment]
这和作者有啥关系，

**Comment by Mr-zhao98** [comment]
等他更新啊

**Comment by gaoyaodad** [comment]
我的天，你们都不知道昨天国家公祭吗，禁娱一天，软件基本都是黑白。

**Comment by Mr-zhao98** [comment]
现在可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gaoyaodad"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 晚上7:42
收件人: "lgpersonal/LazyStudy"<LazyStudy@noreply.github.com&gt;; 
抄送: "倾听者"<1761630764@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lgpersonal/LazyStudy] 今天强国升级，本地浏览灰色，导致浏览不能继续， (#71)





 
我的天，你们都不知道昨天国家公祭吗，禁娱一天，软件基本都是黑白。
